version: "3.3"

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy    
    ports:
      - 80:80
      - 33066:33066
      - 33067:33067
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  simple-app: 
    image: shqkel/simple-app
    container_name: simple-app
    ports: 
      - 8080:8080

  mysql-dev1:
      build: .
      container_name: mysql-dev1
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: 1234
      volumes:
      - ./db-data1:/var/lib/mysql
      ports:
      - 3307:3306
  
  mysql-dev2:
      build: .
      container_name: mysql-dev2
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: 1234
      ports:
      - 3308:3306
      volumes:
      - ./db-data2:/var/lib/mysql
  
  mysql-dev3:
      build: .
      container_name: mysql-dev3
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: 1234
      ports:
      - 3309:3306
      volumes:
      - ./db-data3:/var/lib/mysql

volumes:
  db-data1:
    driver: local
  db-data2:
    driver: local
  db-data3:
    driver: local
